### ISSUE TITLE
storage volumes question

### ISSUE THREAD

**Issue by phatpaul** [WhiteBahamut/nextcloud#2]
Thanks for sharing your setup.  I'm trying to set up something similar on 4 AtomicPis (x86).   I have a RAID5 NAS (CIFS or NFS) which I want to hold all the data and db.  

How did set up your volumes?

**Comment by WhiteBahamut** [comment]
oh man, forgot I even had this up here 👍 
I had simple local path mapping. All my PIs had a nfs mounted in `/mnt/volumes` and there I had subfolder for my apps, e.g. `/mnt/volumes/nextcloud/data`. had some trouble with it and I would suggest to go directly do nfs volumes within the compose (see [here](https://stackoverflow.com/questions/30491449/nfs-volumes-in-docker-docker-compose))
```yml
volumes:
  nextcloud-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.1,rw
      device: ":/mnt/volumes/nextcloud/data"
```

Hope it helps.
